ahoyapi: v2
commands:

  log:php:
    usage: Get lines of /var/log/php.access.log with useful filters
    cmd: ./scripts/platformsh-recipes/logs/php.sh "$@"

  log:php:rpm:
    usage: Get rpm out of /var/log/php.access.log
    cmd: ./scripts/platformsh-recipes/logs/php-rpm.sh "$@"

  log:php:top:
    usage: Get a sorted list of php pages by time. (--mem to sort by memory usage)
    cmd: ./scripts/platformsh-recipes/logs/php-top.sh "$@"

  log:access:
    usage: Get lines of /var/log/access.log with useful filters
    cmd: ./scripts/platformsh-recipes/logs/access.sh "$@"

  log:access:rpm:
    usage: Get rpm out of /var/log/access.log
    cmd: ./scripts/platformsh-recipes/logs/access-rpm.sh "$@"

  log:ipblock:
    usage: Block BAD IPs
    cmd: ./scripts/platformsh-recipes/logs/ipblock.sh "$@"
